# Generated by Django 2.2.4 on 2019-08-05 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JenisBarang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Peminjam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=15)),
                ('nama', models.CharField(max_length=50)),
                ('jk', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=30)),
                ('nama', models.CharField(max_length=80)),
                ('jumlah', models.CharField(max_length=3)),
                ('kondisi', models.CharField(choices=[('Bagus', 'Bagus'), ('Rusak', 'Rusak')], max_length=5)),
                ('jenis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.JenisBarang')),
            ],
        ),
    ]
