# Generated by Django 2.2.4 on 2019-08-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjam',
            name='jk',
            field=models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1),
        ),
    ]
